// Generated by CoffeeScript 2.3.2
var colors, noop;

colors = {
  // saturated colors
  red: [5, 0, 0],
  blue: [0, 1, 5],
  green: [0, 5, 1],
  yellow: [5, 5, 0],
  cyan: [0, 3, 4],
  pink: [5, 0, 4],
  // light colors
  lred: [5, 0, 1],
  lblue: [3, 3, 5],
  lgreen: [0, 5, 3],
  lyellow: [5, 5, 2],
  lcyan: [1, 4, 5],
  lpink: [5, 1, 4],
  // grayscale
  white: [5, 5, 5],
  silver: [4, 4, 4],
  gray: [2, 2, 2],
  coal: [1, 1, 1],
  black: [0, 0, 0]
};

noop = function(arg) {
  return arg;
};

module.exports = function(log, colorEnabled) {
  var getRgb, wrap;
  if (!colorEnabled) {
    log.bold = noop;
    Object.keys(colors).forEach(function(key) {
      return log[key] = noop;
    });
    return;
  }
  wrap = function(a, b, msg) {
    return '\x1b[' + a + 'm' + msg + '\x1b[' + b + 'm';
  };
  getRgb = function([r, g, b]) {
    return '38;5;' + (16 + (36 * r) + (6 * g) + b);
  };
  log.bold = function(msg) {
    if (msg === '') {
      return '';
    } else {
      return wrap(1, 22, msg);
    }
  };
  return Object.keys(colors).forEach(function(key) {
    var color;
    color = getRgb(colors[key]);
    return log[key] = function(msg) {
      if (msg === '') {
        return '';
      } else {
        return wrap(color, 0, msg);
      }
    };
  });
};
