// Generated by CoffeeScript 2.3.0
var DEBUG, NO_COLOR, NO_WARNINGS, TRACE_WARNINGS, colorize, createLog, createWriter, def, env, format, getPrefix, hasFlag, inspect, isCLI, isQuiet, log, methods, quiet;

colorize = require('./colorize');

hasFlag = require('has-flag');

def = Object.defineProperty;

env = typeof process !== 'undefined' ? process.env : window;

isCLI = typeof window === 'undefined';

hasFlag = isCLI ? require('has-flag') : function() {
  return false;
};

isQuiet = hasFlag('--quiet') || env.QUIET === '1';

NO_WARNINGS = hasFlag('--no-warnings') || env.NO_WARNINGS === '1';

NO_COLOR = isCLI && process.stdout.isTTY ? hasFlag('--no-color') || env.NO_COLOR === '1' : env.COLOR !== '1';

TRACE_WARNINGS = !NO_WARNINGS ? hasFlag('--trace-warnings') || env.TRACE_WARNINGS === '1' : false;

quiet = function() {}; // no-op

quiet.write = function() {}; // no-op

colorize(quiet, !NO_COLOR);

methods = {
  warn: null,
  error: null,
  write: null,
  prefix: null,
  clear: null
};

if (!isQuiet) {
  colorize(methods, !NO_COLOR);
  methods.prefix = function(prefix) {
    return def(this, '_prefix', {
      value: typeof prefix === 'function' && prefix || function() {
        return prefix;
      },
      configurable: true
    });
  };
}

getPrefix = function(self, label) {
  var str;
  str = label ? self._prefix && self._prefix() + ' ' + label || label : self._prefix && self._prefix() || '';
  if (log !== self && log._prefix) {
    return str && log._prefix() + ' ' + str || log._prefix();
  }
  return str;
};

if (isCLI) {
  inspect = (function() {
    var opts, util;
    util = require('util');
    opts = {
      colors: !NO_COLOR,
      depth: 1
    };
    return function(arg) {
      return util.inspect(arg, opts);
    };
  })();
  format = function(arg, type) {
    switch (type) {
      case '%s':
        return String(arg);
      case '%O':
        return inspect(arg);
      case '%d':
      case '%f':
        return Number(arg);
      case '%i':
        return parseInt(arg);
      default:
        return arg;
    }
  };
  createWriter = function(stream, label) {
    return function(...args) {
      var arg, i, input, match, offset, output, pattern, prefix;
      i = 0;
      prefix = getPrefix(this, label);
      output = '';
      if (typeof args[0] === 'string') {
        input = args[i++];
        offset = 0;
        pattern = /%[dfisO]/g;
        while (match = pattern.exec(input)) {
          arg = args[i++];
          output += input.slice(offset, match.index) + format(arg, match[0]);
          offset = match.index + 2;
        }
        output += input.slice(offset);
      }
      while (i < args.length) {
        if (i > 0) {
          output += ' ';
        }
        output += inspect(args[i++]);
      }
      output && (output = prefix + ' ' + output);
      stream.write(output + '\n');
    };
  };
  methods.warn = !NO_WARNINGS ? createWriter(process.stdout, quiet.yellow('warn:')) : function() {}; // no-op
  methods.error = createWriter(process.stderr, quiet.red('error:'));
  if (!isQuiet) {
    methods.write = createWriter(process.stdout);
    methods.clear = function() {
      // print line breaks until the screen is empty
      process.stdout.write('\x33[2J');
      // clear the scroll history
      process.stdout.write('\u001b[H\u001b[2J\u001b[3J');
    };
  }
  if (TRACE_WARNINGS) {
    (function() {
      var warn;
      ({warn} = methods);
      return methods.warn = function() {
        var err, stack;
        warn(...arguments);
        err = new Error;
        Error.captureStackTrace(err, arguments.callee);
        stack = err.stack;
        console.log(stack.slice(stack.indexOf('\n') + 1));
      };
    })();
  }
} else {
  createWriter = function(write) {
    return function($1, ...args) {
      var $0;
      if (!($0 = getPrefix(this))) {
        write($1, ...args);
        return;
      }
      if (!args.length && $1 === '') {
        write($1);
        return;
      }
      if (typeof $1 !== 'string') {
        write($0, $1, ...args);
        return;
      }
      write($0 + ' ' + $1, ...args);
    };
  };
  methods.warn = !NO_WARNINGS ? createWriter(console.warn) : function() {}; // no-op
  methods.error = createWriter(console.error);
  if (!isQuiet) {
    methods.write = createWriter(console.log);
    methods.clear = console.clear;
  }
}

// Warnings and errors are not disabled by --quiet
quiet.warn = methods.warn;

quiet.error = methods.error;

// Ignore any property mutation.
Object.freeze(quiet);

createLog = function() {
  var log;
  log = function(...args) {
    return log.write(...args);
  };
  return Object.assign(log, methods);
};

if (isQuiet) {
  log = function() {}; // no-op
  Object.assign(log, quiet);
} else {
  log = createLog();
  if (DEBUG = env.DEBUG) {
    if (hasFlag('--debug') || /^(\*|1)$/.test(DEBUG)) {
      DEBUG = {
        test: function() {
          return true;
        }
      };
    } else {
      DEBUG = DEBUG.replace(/\*/g, '.*').replace(/,/g, '|');
      DEBUG = new RegExp('^(' + DEBUG + ')$');
    }
    log.debug = function(id) {
      return DEBUG.test(id) && createLog() || quiet;
    };
  }
}

log.debug || (log.debug = function() {
  return quiet;
});

log.prefix || (log.prefix = function() {
  return this;
});

log.create || (log.create = isQuiet ? function() {
  return quiet;
} : createLog);

module.exports = log;
